### ISSUE TITLE
    const { post, errors } = useForm(initialFormValues) not working

### ISSUE THREAD

**Issue by Aigarsss** [aviemet/useInertiaForm#12]
Hi, noticed that the post/errors are not working.

When I use post, the "data" values sent to post are not being update by setData (the initial values are sent). I also tried to log out the errors, that is also empty. Works as expected with useForm.

Does it work fine for you?

**Comment by aviemet** [comment]
Could you provide an example, maybe on codesandbox or something similar?

**Comment by Aigarsss** [comment]
Not sure if it will be possible to do it in the sandbox, as we need the full inertia/laravel setup, but you should be able to easily replicate locally.

We should be able to test it by just using the following:

const initialFormValues = {
        title: ""
}

`const { data, setData, post } = useInertiaForm(initialFormValues);` // This doesn't work
vs
`const { data, setData, post } = useForm(initialFormValues);` // this works
```

const submitForm = (e: FormEvent<HTMLFormElement>): void => {
    e.preventDefault();
    post("/");
}

return (
    <form onSubmit={(e) => submitForm(e)}>
        <input
            id="title"
            name="title"
            value={data.title}
            onChangeHandler={(e) => setData("title", e)}
         />
     </form>
)

```
I can see in the network request, that in the useForm `post`, the updated payload is sent as expected, but in useInertiaForm, the payload is not updated, and the initialFormValues is being sent on `post` instead.

**Comment by aviemet** [comment]
The first thing I notice is that you have `onChangeHandler` in your input, which is not a prop. You're also passing the input change event directly to `setData`, which is expecting a primitive value type.

If I paste the code you provided into a project as is, I get console errors, but changing it to the following works for me:

```typescript
const SomeFormComponent = () => {
  const initialFormValues = {
    title: '',
  }

  const { getData, setData, post } = useInertiaForm(initialFormValues)

  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault()
    post('/')
  }

  return (
    <form onSubmit={ handleSubmit }>
      <input
        id="title"
        name="title"
        value={ getData('title') }
        onChange={ e => setData('title', e.target.value) }
      />
    </form>
  )
}
```

Not sure if that was copied directly from your project, but if it was, the call to `setData` never would have triggered because `onChangeHandler` would have been ignored as a non-existent html attribute by React. If these mistakes didn't exist in your project, I'll need to get a reproducible error to track down the issue. You could fork [the example I have on codesandbox](https://codesandbox.io/p/sandbox/useinertiaform-examples-0so45f?file=%2Fsrc%2Findex.tsx) for a project with the proper dependencies already installed.

**Comment by Aigarsss** [comment]
My apologies, while I was trying to add a simplified version of the form and forgot to change the `onChangeHandler` to `onChange`. The example you provided is exactly what I meant. 

I might be doing something wrong, but the codesandbox doesn't allow post or router.post, throws `(0 , G.default) is not a function`.
https://codesandbox.io/p/sandbox/brave-mendel-34sycv - this is the example in theory. The console log would log out the correct `data` value, but the post request would send the `initialFormValues` in the actual network request.

**Comment by aviemet** [comment]
So, I was able to reproduce the error on a local project. You were indeed correct that the HTTP verb methods weren't working. I believe it was due to memoizing them in an attempt to make them stable for dependency arrays. I removed the memoization and they now appear to be functioning as expected for me. #14 

Thank you for bringing this to my attention. I don't use the hook itself, I use the Form component from this package, so I never had the opportunity to see it fail. Please let me know if this fixes things for you.

**Comment by Aigarsss** [comment]
Yes, looks like this fixes it. Thanks a bunch.
